language: php
php:
  - "5.3"
  - "5.4"

script: "ant dev"

before_script:
 - phpenv rehash > /dev/null

notifications:
  email:
    recipients:
     - ts@websafe.pl
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - https://webhook.websafe.pl/notify
      - http://webhook.websafe.pl/notify
    on_success: always
    on_failure: always
    on_start: true
